name: RK3588 images
on: [push]

jobs:
    build:
        name: Build RK3588 Images
        runs-on: ubuntu-latest
        steps:
            - name: Setup Ubuntu
              run: |
               sudo apt update
               sudo apt install -y python3 python3-pip python3-ply python3-distutils python3-pyelftools libpython3-dev swig
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v3
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf rpi5/* openwrt/
                cd openwrt
                git apply 0001-rk3568-88.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/f6db007367a22a31f9cb1c109a032b45/raw/be368c4f1605f652a001d81548c3a3e14adf6cb7/luci-app-diskman.patch
                git apply luci-app-diskman.patch
                cd -
                cd  feeds/packages
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                git apply 20-lxc.patch
                git apply 01-cpu.patch
                cd -
                sed -i "70s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "83s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "194s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "211s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                sed -i 's/default n/default y/g' feeds/packages/utils/dockerd/Config.in
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                wget https://gist.githubusercontent.com/mj22226/84281c9a52b6518631c775222a2cde2e/raw/fe72098ff49c73ff2b0f3eebee03f123690a2b07/10.patch
                git apply 10.patch
                sed -i "73s/# CONFIG_ARM_ROCKCHIP_CPUFREQ is not set/CONFIG_ARM_ROCKCHIP_CPUFREQ=y/" target/linux/rockchip/armv8/config-6.1
                mv config.buildinfo3 .config
                make defconfig
                make download -j32
                rm -rf files
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/rockchip/armv8/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Create release
              uses: ncipollo/release-action@v1.13.0
              with:
                allowUpdates: true
                name: RK3588 Images ${{ env.D }}
                tag: rk3588-${{ env.D }}
                replacesArtifacts: true
                prerelease: false
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*
