name: RPi5 images
on:
   workflow_dispatch:
   schedule:
    - cron: '01 00 * * *'

jobs:
    build:
        name: Build RPi5 Images
        runs-on: ubuntu-latest
        steps:
            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@v2
              with:
                token: ${{ github.token }}
                repository: ${{ github.repository }}
                retain_days: 0
                keep_minimum_runs: 0
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf rpi5/* openwrt/
                cd openwrt
                wget https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2712/llvm-bpf-15.0.7.Linux-x86_64.tar.xz
                wget https://github.com/mj22226/openwrt/commit/33b5077e6bc73e358adab7d3679293eb55a43c71.patch
                wget https://github.com/mj22226/openwrt/commit/f0585b1283f13bfb5c0e64f2341745a848dc621f.patch
                wget https://github.com/mj22226/openwrt/commit/079c7ea2c7dd5c0d17b47e7d1b2981e9ec8fe576.patch
                wget https://github.com/mj22226/openwrt/commit/ef71d0ebe9f9e7dec16eb7c070a674ac5a00b2b7.patch
                wget https://github.com/mj22226/openwrt/commit/c34e77bd13c7a7d1d90d7712fd5a0920f31904b7.patch
                wget https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/15090.patch
                git apply 33b5077e6bc73e358adab7d3679293eb55a43c71.patch
                git apply f0585b1283f13bfb5c0e64f2341745a848dc621f.patch
                git apply 079c7ea2c7dd5c0d17b47e7d1b2981e9ec8fe576.patch
                git apply ef71d0ebe9f9e7dec16eb7c070a674ac5a00b2b7.patch
                git apply c34e77bd13c7a7d1d90d7712fd5a0920f31904b7.patch
                git apply 15090.patch
                tar -xvf llvm-bpf-15.0.7.Linux-x86_64.tar.xz
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/69b47c9a972e15056f94870d76d93a5146893f99/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                cd  feeds/packages
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                wget https://github.com/mj22226/packages/commit/3afa50b894e9bc35db470643316a3e242f9d84bc.patch
                git apply 01-cpu.patch
                git apply 20-lxc.patch
                git apply 3afa50b894e9bc35db470643316a3e242f9d84bc.patch
                cd -
                sed -i "71s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "84s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "195s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "212s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                sed -i 's/default n/default y/g' feeds/packages/utils/dockerd/Config.in
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                sed -i '129d' package/base-files/Makefile
                sed -i '135d' package/base-files/Makefile
                mkdir -p files/www/repo
                mv config.buildinfo .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                cp -R bin/targets/bcm27xx/bcm2712/packages/ files/www/repo/
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/bcm27xx/bcm2712/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
                echo "HASH=$(git log -1 --format="%H")" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: rpi5
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: RPi5 Images ${{ env.D }}
                tag: rpi5
                replacesArtifacts: true
                prerelease: false
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/bcm27xx/bcm2712/*
